--  Generate iconFontsTblDef.lua file.
--    by dinau 2025/03
--  Exectution
--  $ ..\..\bin\luajit makeIconFontsTblDef.lua

---------------------------
--- Only for Windows OS ---
---------------------------

local saveName = "iconFontsTblDef.lua"
local iconFontFile = "..\\..\\bin\\lua\\mylib\\fonticon\\IconsFontAwesome6.lua"
local content = ""

local length = 0
for line in io.lines(iconFontFile) do
  local iconName = line:match(".+(ICON_FA.+)%s=.+")
  if iconName ~= nil then
    local str = [[  ffi.cast("const char*", ]]
    content = content .. str .. "IFA." .. iconName .. " .. "  .. "\"" .. "  " .. iconName .. " \"" .. "),\n"
    length = length + 1
  end
end

-----------------
--- iconFontsTbl
-----------------
content = [[M.iconFontsTbl = ffi.new("const char*[?]",]] .. "M.len"  .. ",{\n" .. content .. "})"
content = [[local IFA   = require"mylib.fonticon.IconsFontAwesome6"]] .. "\n\n" .. content
content = [[local ffi   = require"ffi"]] .. "\n" .. content
content = "M.len = " ..  length .. "\n" .. content
content = "local M = {}\n\n" .. content
content = content .. "\n"
content =
[[
-- DON'T EDIT THIS FILE
-- This file has been auto generated by "make gen"
]]
.. "\n" .. content

------------------
--- iconFontsTbl2
------------------
local content2 = ""
for line in io.lines(iconFontFile) do
  local iconName = line:match(".+(ICON_FA.+)%s=.+")
  if iconName ~= nil then
    content2 = content2 .. "\n  {IFA." .. iconName .. ", "  .. "\"  " .. iconName .. " \"},"
  end
end

content2 = "\n\nM.iconFontsTbl2 = {" .. content2 .. "\n}"

content2 = content2 .. "\n\nreturn M"

local fp = io.open(saveName, "w")
if fp then
  fp:write(content)
  fp:write(content2)
  fp:close()
end

-- end
print(string.format("\n%s", [[
------------
End porcess
------------]]))
print(string.format("Generated: ./%s", saveName))
